# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card.ui'
#
# Created: Wed Mar 28 08:40:35 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.dati = QtGui.QTableWidget(self.centralwidget)
        self.dati.setGeometry(QtCore.QRect(310, 30, 461, 511))
        self.dati.setRowCount(32)
        self.dati.setColumnCount(8)
        self.dati.setObjectName(_fromUtf8("dati"))
        self.dati.horizontalHeader().setVisible(True)
        self.dati.horizontalHeader().setCascadingSectionResizes(False)
        self.dati.horizontalHeader().setDefaultSectionSize(52)
        self.leggi = QtGui.QPushButton(self.centralwidget)
        self.leggi.setGeometry(QtCore.QRect(20, 470, 99, 27))
        self.leggi.setObjectName(_fromUtf8("leggi"))
        self.connetti = QtGui.QPushButton(self.centralwidget)
        self.connetti.setGeometry(QtCore.QRect(20, 430, 99, 27))
        self.connetti.setObjectName(_fromUtf8("connetti"))
        self.disconnetti = QtGui.QPushButton(self.centralwidget)
        self.disconnetti.setGeometry(QtCore.QRect(140, 430, 99, 27))
        self.disconnetti.setObjectName(_fromUtf8("disconnetti"))
        self.sblocca = QtGui.QPushButton(self.centralwidget)
        self.sblocca.setGeometry(QtCore.QRect(140, 470, 99, 27))
        self.sblocca.setObjectName(_fromUtf8("sblocca"))
        self.pin = QtGui.QLineEdit(self.centralwidget)
        self.pin.setGeometry(QtCore.QRect(20, 50, 71, 27))
        self.pin.setMaxLength(3)
        self.pin.setObjectName(_fromUtf8("pin"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.stato_carta = QtGui.QLabel(self.centralwidget)
        self.stato_carta.setGeometry(QtCore.QRect(100, 40, 201, 41))
        self.stato_carta.setText(_fromUtf8(""))
        self.stato_carta.setWordWrap(True)
        self.stato_carta.setObjectName(_fromUtf8("stato_carta"))
        self.scrivi = QtGui.QPushButton(self.centralwidget)
        self.scrivi.setEnabled(False)
        self.scrivi.setGeometry(QtCore.QRect(20, 510, 99, 27))
        self.scrivi.setObjectName(_fromUtf8("scrivi"))
        self.change_pin = QtGui.QPushButton(self.centralwidget)
        self.change_pin.setEnabled(False)
        self.change_pin.setGeometry(QtCore.QRect(140, 510, 99, 27))
        self.change_pin.setObjectName(_fromUtf8("change_pin"))
        self.bit_1 = QtGui.QCheckBox(self.centralwidget)
        self.bit_1.setGeometry(QtCore.QRect(20, 200, 21, 22))
        self.bit_1.setText(_fromUtf8(""))
        self.bit_1.setObjectName(_fromUtf8("bit_1"))
        self.bit_2 = QtGui.QCheckBox(self.centralwidget)
        self.bit_2.setGeometry(QtCore.QRect(40, 200, 21, 22))
        self.bit_2.setText(_fromUtf8(""))
        self.bit_2.setObjectName(_fromUtf8("bit_2"))
        self.bit_3 = QtGui.QCheckBox(self.centralwidget)
        self.bit_3.setGeometry(QtCore.QRect(60, 200, 21, 22))
        self.bit_3.setText(_fromUtf8(""))
        self.bit_3.setObjectName(_fromUtf8("bit_3"))
        self.bit_4 = QtGui.QCheckBox(self.centralwidget)
        self.bit_4.setGeometry(QtCore.QRect(80, 200, 21, 22))
        self.bit_4.setText(_fromUtf8(""))
        self.bit_4.setObjectName(_fromUtf8("bit_4"))
        self.bit_5 = QtGui.QCheckBox(self.centralwidget)
        self.bit_5.setGeometry(QtCore.QRect(100, 200, 21, 22))
        self.bit_5.setText(_fromUtf8(""))
        self.bit_5.setObjectName(_fromUtf8("bit_5"))
        self.bit_6 = QtGui.QCheckBox(self.centralwidget)
        self.bit_6.setGeometry(QtCore.QRect(120, 200, 21, 22))
        self.bit_6.setText(_fromUtf8(""))
        self.bit_6.setObjectName(_fromUtf8("bit_6"))
        self.bit_7 = QtGui.QCheckBox(self.centralwidget)
        self.bit_7.setGeometry(QtCore.QRect(140, 200, 21, 22))
        self.bit_7.setText(_fromUtf8(""))
        self.bit_7.setObjectName(_fromUtf8("bit_7"))
        self.bit_8 = QtGui.QCheckBox(self.centralwidget)
        self.bit_8.setGeometry(QtCore.QRect(160, 200, 21, 22))
        self.bit_8.setText(_fromUtf8(""))
        self.bit_8.setObjectName(_fromUtf8("bit_8"))
        self.bit_9 = QtGui.QCheckBox(self.centralwidget)
        self.bit_9.setGeometry(QtCore.QRect(20, 230, 21, 22))
        self.bit_9.setText(_fromUtf8(""))
        self.bit_9.setObjectName(_fromUtf8("bit_9"))
        self.bit_10 = QtGui.QCheckBox(self.centralwidget)
        self.bit_10.setGeometry(QtCore.QRect(40, 230, 21, 22))
        self.bit_10.setText(_fromUtf8(""))
        self.bit_10.setObjectName(_fromUtf8("bit_10"))
        self.bit_11 = QtGui.QCheckBox(self.centralwidget)
        self.bit_11.setGeometry(QtCore.QRect(60, 230, 21, 22))
        self.bit_11.setText(_fromUtf8(""))
        self.bit_11.setObjectName(_fromUtf8("bit_11"))
        self.bit_12 = QtGui.QCheckBox(self.centralwidget)
        self.bit_12.setGeometry(QtCore.QRect(80, 230, 21, 22))
        self.bit_12.setText(_fromUtf8(""))
        self.bit_12.setObjectName(_fromUtf8("bit_12"))
        self.bit_13 = QtGui.QCheckBox(self.centralwidget)
        self.bit_13.setGeometry(QtCore.QRect(100, 230, 21, 22))
        self.bit_13.setText(_fromUtf8(""))
        self.bit_13.setObjectName(_fromUtf8("bit_13"))
        self.bit_14 = QtGui.QCheckBox(self.centralwidget)
        self.bit_14.setGeometry(QtCore.QRect(120, 230, 21, 22))
        self.bit_14.setText(_fromUtf8(""))
        self.bit_14.setObjectName(_fromUtf8("bit_14"))
        self.bit_15 = QtGui.QCheckBox(self.centralwidget)
        self.bit_15.setGeometry(QtCore.QRect(140, 230, 21, 22))
        self.bit_15.setText(_fromUtf8(""))
        self.bit_15.setObjectName(_fromUtf8("bit_15"))
        self.bit_16 = QtGui.QCheckBox(self.centralwidget)
        self.bit_16.setGeometry(QtCore.QRect(160, 230, 21, 22))
        self.bit_16.setText(_fromUtf8(""))
        self.bit_16.setObjectName(_fromUtf8("bit_16"))
        self.bit_17 = QtGui.QCheckBox(self.centralwidget)
        self.bit_17.setGeometry(QtCore.QRect(20, 260, 21, 22))
        self.bit_17.setText(_fromUtf8(""))
        self.bit_17.setObjectName(_fromUtf8("bit_17"))
        self.bit_18 = QtGui.QCheckBox(self.centralwidget)
        self.bit_18.setGeometry(QtCore.QRect(40, 260, 21, 22))
        self.bit_18.setText(_fromUtf8(""))
        self.bit_18.setObjectName(_fromUtf8("bit_18"))
        self.bit_19 = QtGui.QCheckBox(self.centralwidget)
        self.bit_19.setGeometry(QtCore.QRect(60, 260, 21, 22))
        self.bit_19.setText(_fromUtf8(""))
        self.bit_19.setObjectName(_fromUtf8("bit_19"))
        self.bit_20 = QtGui.QCheckBox(self.centralwidget)
        self.bit_20.setGeometry(QtCore.QRect(80, 260, 21, 22))
        self.bit_20.setText(_fromUtf8(""))
        self.bit_20.setObjectName(_fromUtf8("bit_20"))
        self.bit_21 = QtGui.QCheckBox(self.centralwidget)
        self.bit_21.setGeometry(QtCore.QRect(100, 260, 21, 22))
        self.bit_21.setText(_fromUtf8(""))
        self.bit_21.setObjectName(_fromUtf8("bit_21"))
        self.bit_22 = QtGui.QCheckBox(self.centralwidget)
        self.bit_22.setGeometry(QtCore.QRect(120, 260, 21, 22))
        self.bit_22.setText(_fromUtf8(""))
        self.bit_22.setObjectName(_fromUtf8("bit_22"))
        self.bit_23 = QtGui.QCheckBox(self.centralwidget)
        self.bit_23.setGeometry(QtCore.QRect(140, 260, 21, 22))
        self.bit_23.setText(_fromUtf8(""))
        self.bit_23.setObjectName(_fromUtf8("bit_23"))
        self.bit_24 = QtGui.QCheckBox(self.centralwidget)
        self.bit_24.setGeometry(QtCore.QRect(160, 260, 21, 22))
        self.bit_24.setText(_fromUtf8(""))
        self.bit_24.setObjectName(_fromUtf8("bit_24"))
        self.bit_25 = QtGui.QCheckBox(self.centralwidget)
        self.bit_25.setGeometry(QtCore.QRect(20, 290, 21, 22))
        self.bit_25.setText(_fromUtf8(""))
        self.bit_25.setObjectName(_fromUtf8("bit_25"))
        self.bit_26 = QtGui.QCheckBox(self.centralwidget)
        self.bit_26.setGeometry(QtCore.QRect(40, 290, 21, 22))
        self.bit_26.setText(_fromUtf8(""))
        self.bit_26.setObjectName(_fromUtf8("bit_26"))
        self.bit_27 = QtGui.QCheckBox(self.centralwidget)
        self.bit_27.setGeometry(QtCore.QRect(60, 290, 21, 22))
        self.bit_27.setText(_fromUtf8(""))
        self.bit_27.setObjectName(_fromUtf8("bit_27"))
        self.bit_28 = QtGui.QCheckBox(self.centralwidget)
        self.bit_28.setGeometry(QtCore.QRect(80, 290, 21, 22))
        self.bit_28.setText(_fromUtf8(""))
        self.bit_28.setObjectName(_fromUtf8("bit_28"))
        self.bit_29 = QtGui.QCheckBox(self.centralwidget)
        self.bit_29.setGeometry(QtCore.QRect(100, 290, 21, 22))
        self.bit_29.setText(_fromUtf8(""))
        self.bit_29.setObjectName(_fromUtf8("bit_29"))
        self.bit_30 = QtGui.QCheckBox(self.centralwidget)
        self.bit_30.setGeometry(QtCore.QRect(120, 290, 21, 22))
        self.bit_30.setText(_fromUtf8(""))
        self.bit_30.setObjectName(_fromUtf8("bit_30"))
        self.bit_31 = QtGui.QCheckBox(self.centralwidget)
        self.bit_31.setGeometry(QtCore.QRect(140, 290, 21, 22))
        self.bit_31.setText(_fromUtf8(""))
        self.bit_31.setObjectName(_fromUtf8("bit_31"))
        self.bit_32 = QtGui.QCheckBox(self.centralwidget)
        self.bit_32.setGeometry(QtCore.QRect(160, 290, 21, 22))
        self.bit_32.setText(_fromUtf8(""))
        self.bit_32.setObjectName(_fromUtf8("bit_32"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 170, 101, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 16, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 16, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 260, 16, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 290, 16, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 200, 16, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 230, 16, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(180, 260, 16, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 290, 16, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.proteggi_n = QtGui.QSpinBox(self.centralwidget)
        self.proteggi_n.setEnabled(False)
        self.proteggi_n.setGeometry(QtCore.QRect(220, 200, 51, 27))
        self.proteggi_n.setMinimum(1)
        self.proteggi_n.setMaximum(32)
        self.proteggi_n.setObjectName(_fromUtf8("proteggi_n"))
        self.proteggi = QtGui.QPushButton(self.centralwidget)
        self.proteggi.setEnabled(False)
        self.proteggi.setGeometry(QtCore.QRect(210, 240, 81, 27))
        self.proteggi.setObjectName(_fromUtf8("proteggi"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.leggi.setText(_translate("MainWindow", "leggi", None))
        self.connetti.setText(_translate("MainWindow", "connetti", None))
        self.disconnetti.setText(_translate("MainWindow", "disconnetti", None))
        self.sblocca.setText(_translate("MainWindow", "sblocca", None))
        self.label_4.setText(_translate("MainWindow", "PIN", None))
        self.scrivi.setText(_translate("MainWindow", "scrivi", None))
        self.change_pin.setText(_translate("MainWindow", "cambia PIN", None))
        self.label.setText(_translate("MainWindow", "Byte protetti", None))
        self.label_2.setText(_translate("MainWindow", "1", None))
        self.label_3.setText(_translate("MainWindow", "9", None))
        self.label_5.setText(_translate("MainWindow", "17", None))
        self.label_6.setText(_translate("MainWindow", "25", None))
        self.label_7.setText(_translate("MainWindow", "8", None))
        self.label_8.setText(_translate("MainWindow", "16", None))
        self.label_9.setText(_translate("MainWindow", "24", None))
        self.label_10.setText(_translate("MainWindow", "32", None))
        self.proteggi.setText(_translate("MainWindow", "proteggi", None))

